name: Laravel
env:
   APP_ENV: testing
   APP_DEBUG: true
   DB_HOST: 127.0.0.1
   DB_PORT: 3306
   DB_DATABASE: adserver_test
   DB_USERNAME: travis
   DB_PASSWORD: ""

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
    - name: before_install
      run: |
          sudo add-apt-repository ppa:ondrej/php -y
          sudo add-apt-repository ppa:adshares/releases -y
          sudo apt-get update -q
          sudo apt-get install libsodium-dev ads -y
    - run: sudo apt-get install php7.4      
    - run: wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.$(lsb_release -cs)_amd64.deb && sudo apt install -y ./wkhtmltox_0.12.6-1.$(lsb_release -cs)_amd64.deb
    - run: sudo apt-get install php7.4-imagick   
#    - run: yes | sudo pecl install imagick
    - run: |        
          mkdir -p /tmp/ads/cache
          chmod 777 -R /tmp/ads
    - run: curl -L https://raw.githubusercontent.com/phpenv/phpenv-installer/master/bin/phpenv-installer | bash      
    - run: /home/runner/.phpenv config-add .travis/php.ini
    - run: |
          composer self-update
          cp .env.testing.dist .env.testing
          mkdir -p storage/app/{invoices,public}
          mkdir -p storage/framework/{sessions,views,cache}
          chmod 777 -R storage
    - run: mysql_tzinfo_to_sql /usr/share/zoneinfo 2>/dev/null | mysql mysql
 
    - name: install
      run: |
        yarn install && yarn run prod
        composer install --no-interaction
    - run: mysql -e 'CREATE DATABASE IF NOT EXISTS adserver_test;'
    - run: mysql -e 'SET GLOBAL explicit_defaults_for_timestamp=1;'
    - run: php artisan migrate
 
    - name: Run Testsuite
      run: composer test-ci
