name: Laravel
env:
   APP_ENV: testing
   APP_DEBUG: true
   DB_HOST: 127.0.0.1
   DB_PORT: 3306
   DB_DATABASE: adserver_test
   DB_USERNAME: root
   DB_PASSWORD: ""

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: ${{ env.DB_DATABASE }}
          MYSQL_USER: ${{ env.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
    - name: before_install
      run: |
          sudo add-apt-repository ppa:ondrej/php -y
          sudo add-apt-repository ppa:adshares/releases -y
          sudo apt-get update -q
          sudo apt-get install libsodium-dev ads -y
#    - run: sudo apt-get install php7.4      
    - run: wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.$(lsb_release -cs)_amd64.deb && sudo apt install -y ./wkhtmltox_0.12.6-1.$(lsb_release -cs)_amd64.deb
#    - run: sudo apt-get install php7.4-imagick   
#    - run: yes | sudo pecl install imagick
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
          php-version: '7.4'
          extensions: imagick, swoole, apcu
          ini-values: xdebug.mode=coverage          
    - run: |        
          mkdir -p /tmp/ads/cache
          chmod 777 -R /tmp/ads
#    - run: curl -L https://raw.githubusercontent.com/phpenv/phpenv-installer/master/bin/phpenv-installer | bash      
#    - run: /home/runner/.phpenv/bin/phpenv config-add .travis/php.ini
    - name: composer
      run: |
          composer self-update
          cp .env.testing.dist .env.testing
          mkdir -p storage/app/{invoices,public}
          mkdir -p storage/framework/{sessions,views,cache}
          chmod 777 -R storage
          
    - run: mysql_tzinfo_to_sql /usr/share/zoneinfo 2>/dev/null | mysql --host 127.0.0.1 --port 3306 -uroot mysql
 
    - name: install
      run: |
        yarn install && yarn run prod
        composer install --no-interaction
    - run: mysql --host 127.0.0.1 --port 3306 -uroot -e 'SET GLOBAL explicit_defaults_for_timestamp=1;'
    - run: php artisan migrate
 
    - name: Run Testsuite
      run: composer test-ci
